# 请求的目标 URL
TARGET_URL = "https://jtnew.lingyunwl.net/api/spfz/linkCopy"

# 要读取的URL列名
URL_COLUMN = "商品链接"

# 用于标记状态的列名
STATUS_COLUMN = "是否发送请求"

# 新增：用于记录发送时间的列名
SEND_TIME_COLUMN = "发送时间"

# 新增：用于记录响应内容的列名
RESPONSE_COLUMN = "response"

# 标记请求成功的状态值
STATUS_SUCCESS_VALUE = "是"

# 每次请求之间的间隔时间（分钟）
REQUEST_INTERVAL_MINUTES = 8

# 新增：随机等待时间的范围（秒）
RANDOM_INTERVAL_SECONDS_MIN = 2
RANDOM_INTERVAL_SECONDS_MAX = 15

# 日志配置
[logging]
LOG_TO_FILE = false
LOG_FILE_PATH = "app.log"
LOG_LEVEL = "DEBUG" # 可选: DEBUG, INFO, WARNING, ERROR, CRITICAL

# 应用配置
[app]
ALLOW_REGISTRATION = false # 是否允许用户注册
DATABASE_URI = "sqlite:///taobaoutils.db" # SQLAlchemy 数据库连接 URI

# 请求的-d参数，占位符 {url} 将被替换为从 Excel 中读取的 URL
[request_payload_template]
sub_user = "747905254"
userids = ["3967358899"]
filter_copied = true
copy_type = 1
param_id = "1811"
is_search = "0"

[[request_payload_template.linkData]]
url = "{url}"
num_iid = ""

# 自定义请求头
[custom_headers]
Appname = "fzbb"
Token = "Ep4u7k425ZsCt3HIgB/WsfI8VfVryYTR/pAz6mvUSX8=" # 请替换为您的实际 Token
